### ISSUE TITLE
[Bug]: 6.5.8 compatibility

### ISSUE THREAD

**Issue by htuscher** [HEPTACOM/HeptacomShopwarePlatformAdminOpenAuth#19]
### Plugin Version

6.0.0

### PHP Version

8.3

### Shopware Version

6.5.8.0

### Installation method

Composer

### Identity provider

None

### What happened?

```
  Problem 1
    - Root composer.json requires heptacom/shopware-platform-admin-open-auth ^6.0 -> satisfiable by heptacom/shopware-platform-admin-open-auth[6.0.0].
    - heptacom/shopware-platform-admin-open-auth 6.0.0 requires symfony/routing ~6.2.0 || ~6.3.0 -> found symfony/routing[v6.2.0, ..., v6.3.11] but it conflicts with your root composer.json require (^6.4).

```

Basically says it all

**Comment by JoshuaBehrens** [comment]
Hi @htuscher , yes we have this issue as well :) do you also need it for the 5.x version or would you just use the 6.x?

**Comment by htuscher** [comment]
6.x is enough. Thanks for asking.

**Comment by phumps** [comment]
Hi @JoshuaBehrens, do you plan to update the plugin for the latest Shopware 6 version?

**Comment by JoshuaBehrens** [comment]
@phumps @jeboehm @htuscher I have a release candidate for this https://github.com/HEPTACOM/HeptacomShopwarePlatformAdminOpenAuth/releases/tag/6.0.1-rc.1 . Please give it a try. In worked for us in testing but we would like to gather feedback from those, who are affected :)

**Comment by JoshuaBehrens** [comment]
We tested it in some more shops now and decided to go for a release. Happy 6.0.1 release everyone :)
