### ISSUE TITLE
[Bug]: Compatibility with 6.5.8.8

### ISSUE THREAD

**Issue by cngJo** [HEPTACOM/HeptacomShopwarePlatformAdminOpenAuth#22]
### Plugin Version

6.0.1

### PHP Version

8.2

### Shopware Version

6.5.8.8

### Installation method

Composer

### Identity provider

Keycloak

### What happened?

With Shopware 6.5.8.8, they introduced a breaking change by adding native types to 
- `Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriterInterface::insert`
- `Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriterInterface::update`

To be fair, it's technically not a breaking change, since the interface is marked as `@internal` and therefore not part of the public API.

The Shopware commit changing this, is https://github.com/shopware/shopware/commit/c1b1d7d8b41de76a58276b44a402718a96982edc.

Just adding a native array return types to those methods in `\Heptacom\AdminOpenAuth\Component\Provider\DefaultInjectingEntityWriterDecorator` should be enough to resolve this.

**Comment by cngJo** [comment]
I'd provide a PR for this today in the evening when there is nothing against is 😉

**Comment by JoshuaBehrens** [comment]
Thank you @cngJo for approaching us with this. We are aware of us going for some internal processes for a better and deeper integration into Shopware. We'd be glad if you create a pull request for this :)

**Comment by silviokennecke** [comment]
Thank you @cngJo . I just merged your PR. Version 6.0.3 will be released soon...
