### ISSUE TITLE
[Bug]: Currently used UserProvisioner class is deprecated - namespace has been moved

### ISSUE THREAD

**Issue by AndreasA** [HEPTACOM/HeptacomShopwarePlatformAdminOpenAuth#9]
### Plugin Version

4.2.1

### PHP Version

8.1

### Shopware Version

6.4.18.1

### Installation method

Composer

### Identity provider

Google Cloud

### What happened?

This is just a minor change, but the USerProvisioner class referenced here https://github.com/HEPTACOM/HeptacomShopwarePlatformAdminOpenAuth/blob/4.2.1/src/Service/UserResolver.php has been deprecated. From what I can see only its namespace has changed (it has been moved to maintenance).

**Comment by JoshuaBehrens** [comment]
Good check from your side. That will only break in 6.5 updates so no need to approach this now. As we are already working on the 6.5 refactoring of our plugin this has been solved as this was a breaking change.
